# dir path should be the relative path of this config file
template_dir: templates
page_dir: ../pages
output_dir: ../public
style_dir: style

sitemap: sitemap.txt

user_name: Ï„
domain: https://yangtau.me
 
