name: deploy

on:
  push:
    # branches: [ main ]

jobs:
  build-site:
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.8' # Resolves to the latest point release of GHC 8.8
          cabal-version: '3.0.0.0' # Exact version of Cabal

      - name: Build
        run: cabal run -j8 site build

      - name: Commit files
        run: |
          git config --local user.email "32403743+yangtau@users.noreply.github.com"
          git config --local user.name "github-actions"
          rm -rf docs && mv _site docs
          touch docs/CNAME && echo "yangtau.me" > docs/CNAME
          git add docs/
          git commit -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-page
          force: true
