# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML Jinja2 markdown pymdown-extensions
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          python yabg/main.py config.yaml
      
      - name: Commit files
        run: |
          git config --local user.email "32403743+yangtau@users.noreply.github.com"
          git config --local user.name "github-actions"
          rm -rf docs && mv public docs
          git add docs/
          git commit -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-page
          force: true
          

